# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: José Manuel LLamas Muñoz
title: Programador / DevOps / Middleware
email: jmfllamas@gmail.com
email_title: Email
phone: 646 406 610
phone_title: Teléfono
website: https://llamasdev.github.io/Blog/
website_title: Blog

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: LLamasDev
github_username:  LLamasDev
linkedin_username: llamasdev
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
  - title: Blog link
    icon: fa fa-globe
    url: https://llamasdev.github.io/Blog/
  - title: Telegram link
    icon: fab fa-telegram
    url: https://t.me/Fib0nacci
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mí
about_profile_image: ./images/LLamasDev.PNG
about_content: |
  Especialista en DevOps y SRE con más de 2 años de experiencia diseñando y gestionando plataformas de observabilidad a gran escala. Mi enfoque es transformar datos complejos en información accionable, utilizando herramientas como la pila TICK, Elastic Stack y Kafka para construir sistemas resilientes, reducir el ruido de alertas y acelerar la resolución de incidentes. Apasionado por la automatización y la cultura de la fiabilidad.
  
content:
  - title: Experiencia
    layout: list
    content:
      - layout: center
        title: Especialista en DevOps, SRE y Observabilidad
        sub_title: DXC
        caption: abr. 2023 - actualidad
        quote: >
        description: |
          Diseño e implementación de la pila TICK: Desplegué y gestioné la infraestructura de monitorización con Telegraf, InfluxDB y Kapacitor para la recolección y análisis en tiempo real de métricas críticas del sistema y aplicaciones.
          
          Análisis avanzado de datos con Flux: Escribí consultas complejas en Flux para transformar datos brutos en Key Performance Indicators (KPIs) accionables, permitiendo una comprensión profunda del comportamiento de la plataforma.
          
          Visualización centralizada con Grafana: Creé dashboards estratégicos en Grafana, unificando la visualización de métricas (desde InfluxDB) y logs (desde Elasticsearch) para proporcionar una vista 360° del estado de los servicios a los equipos de desarrollo y operaciones.
          
          Gestión de logs a escala con Elastic Stack: Implementé la pila ELK para construir un sistema centralizado de logging. Utilicé Logstash para la ingesta y enriquecimiento, y Kibana para facilitar el análisis de causa raíz y la resolución de incidentes (troubleshooting).
          
          Pipeline de datos robusto con Kafka: Integré Apache Kafka para crear un pipeline de streaming resiliente, garantizando la ingesta de altos volúmenes de logs y métricas sin pérdida de datos y desacoplando los sistemas productores de los consumidores.
          
          Estrategia de alertas inteligente: Desarrollé un sistema de alertas proactivo combinando la potencia de Kapacitor con el enrutamiento de Alerta.io para reducir el ruido, minimizar la fatiga por alertas y asegurar que las notificaciones críticas llegaran al equipo correcto de forma inmediata.
          
          Automatización de la Observabilidad: Automaticé la creación de alertas dinámicas mediante scripts en Python y Bash, que analizan patrones de métricas para detectar anomalías que los umbrales estáticos no pueden capturar.
          
          Infraestructura como código (IaC) para Observabilidad: Utilicé Docker para contenerizar y desplegar toda la pila de herramientas de monitorización, asegurando consistencia, reproducibilidad y agilidad en la gestión de la infraestructura.
      - layout: center
        title: Técnico administrador de sistemas Middleware
        sub_title: Infortec
        caption: ene. de 2022 - abr. 2023 (1 año 4 meses)
        quote: >
        description: |
          Cliente: Movistar
          - Parada, arranque y revisión de: Apache Webserver, Oracle WebLogic Server, JBoss y Tomcat.
          - Creación o edición de script en bash.
          - Spazio: parada y arranque de spazio o de líneas, revisión de colas, visualización de ficheros en colas, crear o eliminar colas.
          - Flujos (Ghibli): Revisión de los flujos, que no siempre tienen que pasar por Spazio.
          - Resolución de incidencias y peticiones por herramienta de ticketing.
          - Herramientas de monitorización.
          - Preparación y ejecución de cambios.
      - layout: center
        title: Técnico administrador de sistemas Middleware
        sub_title: Inetum
        caption: ago. de 2020 - ene. de 2022 (1 año 6 meses)
        quote: >
        description: |
          Cliente: Movistar
          - Conocimientos de herramientas como: Clarive, OEM 13c (Oracle Enterprise Manager Cloud Control 13c), ODI (Oracle Database Interface).
          - Parada, arranque y revisión de: Apache Webserver, Oracle WebLogic Server, JBoss y Tomcat.
          - Resolución de incidencias y peticiones por herramienta de ticketing.
          - Herramientas de monitorización.
          - Conocimientos de OPENSHIFT, Tuxedo y MQ-SPAZIO.
          - Preparación y ejecución de cambios.
      - layout: top
        title: Soporte técnico para empresas de Orange
        sub_title: Majorel
        caption: oct. de 2017 - mar. de 2020 (2 años 6 meses)
      - layout: top
        title: Practicas IT
        sub_title: Colegio Laude El Altillo school
        caption: abr. de 2017 - jun. de 2017 (3 meses)

  - title: Proyectos
    layout: list
    content:
      - layout: left
        title: Clash Royale
        link: https://github.com/LLamasDev/ClashRoyale
        link_text: Clash Royale
        additional_links:
          - title: Clash Royale
            icon: fab fa-github
            url: https://github.com/LLamasDev/ClashRoyale
        quote: >
        description: |
          Bot creado en Python para Telegram (tanto en grupos como por privado) para obtener mediante la API oficial información de tu cuenta, de tu clan en el juego, indicando los mazos más usados o ayuda al usuario a gestionar su clan proporcionando información de los eventos. Con una base de datos para almacenar la configuración del usuario o llevar un control de uso para sacar estadísticas.
      - layout: left
        title: Clash Royale API
        link: https://github.com/LLamasDev/ClashRoyaleAPI
        link_text: Clash Royale API
        additional_links:
          - title: API de peticiones GET y POST
            icon: fab fa-github
            url: https://github.com/LLamasDev/ClashRoyaleAPI
        quote: >
        description: |
          Proyecto realizado en Python y Django, realiza funciones como [Clash Royale](https://github.com/LLamasDev/ClashRoyale), pero con la función extra de ser una API propia que admite peticiones GET y POST.
      - layout: left
        title: Gestión de procesos Bash
        link: https://github.com/LLamasDev/administrador-bash
        link_text: Gestión de procesos Bash
        additional_links:
          - title: Gestión de procesos Bash
            icon: fab fa-github
            url: https://github.com/LLamasDev/administrador-bash
        quote: >
        description: |
          Son scripts en Bash para ver si un proceso está corriendo, arrancar un proceso, parar un proceso o reiniciar un proceso.
      - layout: left
        title: Web Scraping
        link: https://github.com/LLamasDev/WebScraping
        link_text: Web Scraping
        additional_links:
          - title: Web Scraping
            icon: fab fa-github
            url: https://github.com/LLamasDev/WebScraping
        quote: >
        description: |
          Proyecto realizado con Beautiful Soup para obtener datos mediante web scraping.

  - title: Educación
    layout: list
    content:
      - layout: top
        title: Desarrollo de Aplicaciones Multiplataforma
        sub_title: IES Almunia
        caption: 2019 - 2021
      - layout: top
        title: Administración de Sistemas Informáticos en Red
        sub_title: IES Romero Vargas
        caption: 2015 - 2017
      - layout: top
        title: Bachillerato de Ciencias y Tecnología
        sub_title: IES Vega del Guadalete
        caption: 2012

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
