# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: José Manuel LLamas Muñoz
title: Programador / DevOps / Middleware
email: jmfllamas@gmail.com
email_title: Email
phone: 646 406 610
phone_title: Teléfono
website: https://llamasdev.github.io/Blog/
website_title: Blog

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: LLamasDev
github_username:  LLamasDev
linkedin_username: llamasdev
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Link name
  - title: Blog link
    icon: fa fa-globe
    url: https://llamasdev.github.io/Blog/
  - title: Telegram link
    icon: fab fa-telegram
    url: https://t.me/Fib0nacci
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mí
about_profile_image: ./images/LLamasDev.PNG
about_content: |
  Mis comienzos en este mundillo fueron creando páginas webs, más tarde estudié ASIR (Administración de Sistemas Informáticos en Red) porque me apasiona el mundo GNU/Linux, pero también me apasiona el mundo de la programación por lo cual terminé estudiando más tarde DAM (Desarrollo de Aplicaciones Multiplataforma) mientras trabajaba.

  Como administrador de sistemas middleware aprendí (Cliente: Movistar):
    - Conocimientos de herramientas como: Clarive, OEM 13c (Oracle Enterprise Manager Cloud Control 13c), ODI (Oracle Database Interface).
    - Parada, arranque y revisión de: Apache Webserver, Oracle WebLogic Server, JBoss y Tomcat.
    - Creación o edición de script en bash.
    - Spazio: parada y arranque de spazio o de líneas, revisión de colas, visualización de ficheros en colas, crear o eliminar colas.
    - Flujos (Ghibli): Revisión de los flujos, que no siempre tienen que pasar por Spazio.
    - Resolución de incidencias y peticiones por herramienta de ticketing.
    - Herramientas de monitorización.
    - Conocimientos de OPENSHIFT, Tuxedo y MQ.
    - Preparación y ejecución de cambios.

  En desarrollo de aplicaciones multiplataforma (DAM) aprendí:
    - Programar en Python, JavaScript, TypeScript (Angular, Ionic), C#, Java, Android(Java).
    - Microsoft SQL Server para la gestión de bases de datos.

  En administración de sistemas informáticos en red (ASIR) aprendí:
    - Virtualización.
    - Administración de GNU/Linux, Windows 7, 8, 10 y Windows server.
    - Bases de datos.
    - Gestión de redes.
    - Programación en bash, Python, PHP y JavaScript.

  Luego por mi cuenta seguí usando GNU/Linux con servidores NAS o VPS para montar mis proyectos como mi bot para [Clash Royale](https://github.com/LLamasDev/ClashRoyale) o profundizar con bash y web scraping, donde fusiono mis dos grandes pasiones, sistemas GNU/Linux y la programación. Más tarde cree mi [blog](https://llamasdev.github.io/Blog/) donde creo procedimientos o apunto datos de interés personal, para acceder rápido a esta información. Nunca me canso de seguir aprendiendo en este fantástico mundo de la informática.

content:
  - title: Experiencia
    layout: list
    content:
      - layout: center
        title: Técnico administrador de sistemas Middleware
        sub_title: Infortec
        caption: ene. de 2022 - actualidad
        quote: >
        description: |
          Cliente: Movistar
          - Parada, arranque y revisión de: Apache Webserver, Oracle WebLogic Server, JBoss y Tomcat.
          - Creación o edición de script en bash.
          - Spazio: parada y arranque de spazio o de líneas, revisión de colas, visualización de ficheros en colas, crear o eliminar colas.
          - Flujos (Ghibli): Revisión de los flujos, que no siempre tienen que pasar por Spazio.
          - Resolución de incidencias y peticiones por herramienta de ticketing.
          - Herramientas de monitorización.
          - Preparación y ejecución de cambios.
      - layout: center
        title: Técnico administrador de sistemas Middleware
        sub_title: Inetum
        caption: ago. de 2020 - ene. de 2022
        quote: >
        description: |
          Cliente: Movistar
          - Conocimientos de herramientas como: Clarive, OEM 13c (Oracle Enterprise Manager Cloud Control 13c), ODI (Oracle Database Interface).
          - Parada, arranque y revisión de: Apache Webserver, Oracle WebLogic Server, JBoss y Tomcat.
          - Resolución de incidencias y peticiones por herramienta de ticketing.
          - Herramientas de monitorización.
          - Conocimientos de OPENSHIFT, Tuxedo y MQ-SPAZIO.
          - Preparación y ejecución de cambios.
      - layout: top
        title: Soporte técnico para empresas de Orange
        sub_title: Majorel
        caption: oct. de 2017 - mar. de 2020
      - layout: top
        title: Practicas IT
        sub_title: Colegio Laude El Altillo school
        caption: abr. de 2017 - jun. de 2017

  - title: Proyectos
    layout: list
    content:
      - layout: left
        title: Clash Royale
        link: https://github.com/LLamasDev/ClashRoyale
        link_text: Clash Royale
        additional_links:
          - title: Clash Royale
            icon: fab fa-github
            url: https://github.com/LLamasDev/ClashRoyale
        quote: >
        description: |
          Bot creado en Python para Telegram (tanto en grupos como por privado) para obtener mediante la API oficial información de tu cuenta, de tu clan en el juego, indicando los mazos más usados o ayuda al usuario a gestionar su clan proporcionando información de los eventos. Con una base de datos para almacenar la configuración del usuario o llevar un control de uso para sacar estadísticas.
      - layout: left
        title: Clash Royale API
        link: https://github.com/LLamasDev/ClashRoyaleAPI
        link_text: Clash Royale API
        additional_links:
          - title: API de peticiones GET y POST
            icon: fab fa-github
            url: https://github.com/LLamasDev/ClashRoyaleAPI
        quote: >
        description: |
          Proyecto realizado en Python y Django, realiza funciones como [Clash Royale](https://github.com/LLamasDev/ClashRoyale), pero con la función extra de ser una API propia que admite peticiones GET y POST.
      - layout: left
        title: Gestión de procesos Bash
        link: https://github.com/LLamasDev/administrador-bash
        link_text: Gestión de procesos Bash
        additional_links:
          - title: Gestión de procesos Bash
            icon: fab fa-github
            url: https://github.com/LLamasDev/administrador-bash
        quote: >
        description: |
          Son scripts en Bash para ver si un proceso está corriendo, arrancar un proceso, parar un proceso o reiniciar un proceso.
      - layout: left
        title: Web Scraping
        link: https://github.com/LLamasDev/WebScraping
        link_text: Web Scraping
        additional_links:
          - title: Web Scraping
            icon: fab fa-github
            url: https://github.com/LLamasDev/WebScraping
        quote: >
        description: |
          Proyecto realizado con Beautiful Soup para obtener datos mediante web scraping.

  - title: Educación
    layout: list
    content:
      - layout: top
        title: Desarrollo de Aplicaciones Multiplataforma
        sub_title: IES Almunia
        caption: 2019 - 2021
      - layout: top
        title: Administración de Sistemas Informáticos en Red
        sub_title: IES Romero Vargas
        caption: 2015 - 2017
      - layout: top
        title: Bachillerato de Ciencias y Tecnología
        sub_title: IES Vega del Guadalete
        caption: 2012

  - title: Certificados
    layout: list
    content:
      - layout: top
        title: Aprende Oracle SQL desde cero
        caption: 2021
      - layout: top
        title: Introducción a SQL con Oracle 11g
        caption: 2021
      - layout: top
        title: Web scraping Extracción de datos en la Web
        caption: 2020
      - layout: top
        title: GIT
        caption: 2020
      - layout: top
        title: Confidencialidad y protección de datos
        caption: 2018
      - layout: top
        title: CCNA1 de Cisco
        caption: 2016
      - layout: top
        title: CCNA2 de Cisco
        caption: 2016
      - layout: top
        title: IT Essentials de Cisco
        caption: 2016

  - title: Datos de interés
    layout: text
    content: |
      - Carnet de conducir - B, vehículo propio y movilidad geográfica
      - Disponibilidad inmediata
      - Gran capacidad de aprendizaje y seguir mejorando
      - Adaptabilidad al proyecto
      - Proactividad
      - Dotes de liderazgo e iniciativa
      - Gran ingenio en resolución de problemas y trabajo en equipo
      - Persona seria y responsable
      - Sociabilidad y destreza en la relación con los clientes
      - Profesionalidad y enfoque hacia objetivos
      - Nivel medio de inglés hablado y escrito

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
